version: '3'
services:
 YOUR_APPLICATION_NAME:
  image: k2xg10rvz/debian:1.0.2
  volumes:
  - ./data/:/www/wwwroot/YOUR_APPLICATION_NAME/
  - ./init/:/www/container/debian/init/
  stdin_open: true
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.100
    
 consul:
  image: consul:1.8.5
  volumes:
   - ./service/consul/data:/consul/data
   - ./service/consul/config:/consul/config
  ports:
   - "8300/tcp"
   - "8301/udp"
   - "8302/udp"
   - "8500/tcp"
   - "8600/udp"
  command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.101

networks:
 app_net:
  external: true