version: '3'
services:

 nginx:
  image: k2xg10rvz/nginx:1.1.2
  volumes:
  - ../application/:/www/wwwroot/
  - ./nginx/init/:/www/container/nginx/init/
  - ./nginx/config/core/:/etc/nginx/config/
  - ./nginx/config/additional/:/etc/nginx/conf.d/
  - ./nginx/config/site/:/etc/nginx/sites-available/
  - ./nginx/log/:/var/log/nginx/
  - ./nginx/_letsencrypt/:/var/www/_letsencrypt/
  - ./nginx/letsencrypt/:/etc/letsencrypt/
  # - /usr/lib/serv/nginx/:/etc/nginx/reserve/
  # - /usr/lib/serv/tmp/:/var/log/reserve/
  ports:
  - "80:80"
  - "443:443"
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.10
    
 mariadb:
  image: mariadb:10.4
  volumes:
  - ./mariadb/config/:/etc/mysql/conf.d/
  - ./mariadb/data/:/var/lib/mysql/
  - ./mariadb/init:/docker-entrypoint-initdb.d
  ports:
  - "MariaDB Port:3306"
  environment:
   MYSQL_ROOT_PASSWORD: YOUR_MARIADB_ROOT_PASSWORD
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.11
    
 redis:
  image: redis:6.0
  volumes:
  - ./redis/data/:/data/
  - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
  command:
    redis-server /usr/local/etc/redis/redis.conf
  ports:
  - "Redis Port:6379"
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.12
    
 postgres:
  image: postgres:12.2
  volumes:
   - ./postgres/config:/etc/postgresql
   - ./postgres/init:/docker-entrypoint-initdb.d
  ports:
   - "Postgres Port:5432"
  environment:
   POSTGRES_USER: postgres_user
   POSTGRES_PASSWORD: postgres_password
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.13
    
 traefik:
 # The official v2 Traefik docker image
  image: traefik:v2.4
  environment:
   - TZ=Asia/Shanghai
  ports:
   # The HTTP port
   - "80"
   # The Web UI (enabled by --api.insecure=true)
   - "8080"
   - "443"
  restart: always
  volumes:
  # So that Traefik can listen to the Docker events
  - /var/run/docker.sock:/var/run/docker.sock
  - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
  - ./traefik/config:/traefik
  - ./traefik/log:/etc/traefik/log
  networks:
   app_net:
    ipv4_address: 192.168.1.14

 # https://github.com/etcd-io/etcd/releases
 etcd:
  image: gcr.io/etcd-development/etcd:v3.2.32
  ports:
  - "2379:2379"
  - "2380:2380"
  volumes:
  - ./etcd/data/:/etcd_data
  command:
   /usr/local/bin/etcd
   --name s1
   --data-dir /etcd-data
   --listen-client-urls http://0.0.0.0:2379
   --advertise-client-urls http://0.0.0.0:2379
   --listen-peer-urls http://0.0.0.0:2380
   --initial-advertise-peer-urls http://0.0.0.0:2380
   --initial-cluster s1=http://0.0.0.0:2380
   --initial-cluster-token tkn
   --initial-cluster-state new
  restart: always
  networks:
   app_net:
    ipv4_address: 192.168.1.15
    
networks:
 app_net:
  external: true